name: Publish NuGet Tool

on:
   push:
      tags:
         - 'v*'

jobs:
   publish:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v3

         - name: Setup .NET
           uses: actions/setup-dotnet@v3
           with:
             dotnet-version: '8.0.x'

         - name: Publish to GitHub Packages
           run: |
             dotnet restore
             dotnet pack -c Release
             dotnet nuget push NugetCleaner/bin/Release/*.nupkg --source "https://nuget.pkg.github.com/kibnet/index.json" --api-key ${{secrets.PACKAGE_TOKEN}} --skip-duplicate
             dotnet nuget push NugetCleaner/bin/Release/*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json --skip-duplicate

